### ISSUE TITLE
Error in Previously Building Notebook with New Version (0.1.8)

### ISSUE THREAD

**Issue by eric-tramel** [greenape/mknotebooks#11]
I had a notebook in a set of documentation which was building normally using this plugin together with a conventional `mkdocs` build using the `mkdocs-material` theme. However, since the latest update, the notebook does not build and instead throws the following error. Any thoughts?

```
ERROR   -  Error reading page '/some/redacted/path/notebook.ipynb': Expected at least four leading whitespaces, but got string: '![png](output_8_0.png)'
Traceback (most recent call last):
  File "/a/redacted/path/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/a/redacted/path/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/a/redacted/path/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/a/redacted/path/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/a/redacted/path/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/a/redacted/path/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/a/redacted/path/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/a/redacted/path/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/a/redacted/path/lib/python3.7/site-packages/mkdocs/commands/build.py", line 170, in _populate_page
    page.read_source(config)
  File "/a/redacted/path/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 126, in read_source
    source = config['plugins'].run_event('page_read_source', None, config=config, page=self)
  File "/a/redacted/path/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/a/redacted/path/lib/python3.7/site-packages/mknotebooks/plugin.py", line 98, in on_page_read_source
    body, resources = exporter.from_notebook_node(nb)
  File "/a/redacted/path/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 322, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/a/redacted/path/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/a/redacted/path/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/a/redacted/path/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/a/redacted/path/lib/python3.7/site-packages/mknotebooks/templates/custom_markdown.tpl", line 22, in top-level template code
    {% extends "markdown.tpl" %}
  File "/a/redacted/path/lib/python3.7/site-packages/nbconvert/exporters/../templates/markdown.tpl", line 1, in top-level template code
    {% extends 'display_priority.tpl' %}
  File "/a/redacted/path/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 1, in top-level template code
    {%- extends 'null.tpl' -%}
  File "/a/redacted/path/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 25, in top-level template code
    {%- endblock header -%}
  File "/a/redacted/path/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 27, in block "body"
    {%- for cell in nb.cells -%}
  File "/a/redacted/path/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 30, in block "any_cell"
    {%- if resources.global_content_filter.include_code -%}
  File "/a/redacted/path/lib/python3.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 40, in block "codecell"
    {%- if cell.outputs and resources.global_content_filter.include_output -%}
  File "/a/redacted/path/lib/python3.7/site-packages/mknotebooks/templates/custom_markdown.tpl", line 33, in block "output_group"
    {{ super().split('\n') | map('remove_leading_indentation') | join('\n') }}
  File "/a/redacted/path/lib/python3.7/site-packages/jinja2/filters.py", line 479, in do_join
    return text_type(d).join(imap(text_type, value))
  File "/a/redacted/path/lib/python3.7/site-packages/jinja2/filters.py", line 1118, in do_map
    yield func(item)
  File "/a/redacted/path/lib/python3.7/site-packages/jinja2/filters.py", line 1285, in func
    name, item, args, kwargs, context=context
  File "/a/redacted/path/lib/python3.7/site-packages/jinja2/environment.py", line 510, in call_filter
    return func(*args, **(kwargs or {}))
  File "/a/redacted/path/lib/python3.7/site-packages/mknotebooks/plugin.py", line 23, in remove_leading_indentation
    raise ValueError(f"Expected at least four leading whitespaces, but got string: {s!r}")
ValueError: Expected at least four leading whitespaces, but got string: '![png](output_8_0.png)
```

**Comment by greenape** [comment]
Hi @eric-tramel - I just pushed 0.1.10 which _should_ solve that. Be much appreciated if you'd let me know either way :)

**Comment by eric-tramel** [comment]
Fast response time @greenape ;) So, with the latest release, indeed the build passes, great!

However, it is now a silent failure, unfortunately :( Inspecting the HTML built out of the notebook, much of the rich content is now broken. Specifically, looking at some Matplotlib figures, one now finds things like

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/1223539/74685735-acf46780-51cf-11ea-8742-bd46bdb08553.png">

Also, outputs on some error messages come with extra HTML accoutrements. Here is a common warning thrown up from Tensorflow, for example:

```
<div class="output_subarea output_stream output_stdout output_text">
<pre>WARNING:tensorflow:From /anaconda3/envs/ruche2/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:642: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
</pre>
</div>
```

**Comment by greenape** [comment]
Oh dear! More haste, less speed.

I've pushed a new version this morning that should hopefully resolve the rich output.

For the warnings, would putting `warnings.filterwarnings("ignore")` in a preamble script solve for you?

**Comment by eric-tramel** [comment]
👏 @greenape 👏 

All seems in working order for me! Images came back into the built HTML output (great). And also, too, the code syntax highlighting is working properly, as well as stdout/err formatting text (e.g. `loguru` outputs), which is also appearing nicely displayed and with proper colors!

**Comment by eric-tramel** [comment]
The only remaining thing, and I don't even know that this is on your side @greenape , is that long warning/log messages do not line break at the cell, but instead run on to the right as long as they'd like to:

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/1223539/74816279-17ee8d00-52fb-11ea-8374-32b4957baf01.png">

Let me know if you'd like to address as a different issue !
